import { Schema, model, Types } from 'mongoose';
import { EMPRESAS, Empresa, RUBROS, Rubro } from '../types/empresa';

/**
 * The main document. One row = one accounting entry (an `asiento` line).
 *
 * `sourceType` distinguishes:
 *   - `ledger`    — parsed from a mayor file during ingesta (bound to a batch).
 *   - `cmv-calc`  — synthetic pseudo-mov generated by the CMV calculator
 *                   (also bound to the batch that produced it).
 *   - `manual`    — entered by the user via /movimientos-manuales for stuff
 *                   the contador doesn't put in the mayor (IIBB, salaries,
 *                   honorarios directores). NOT bound to a batch — survives
 *                   re-ingestas of the period.
 *
 * `numeroCuentaReimputada` is a string because some reimputation targets
 * are non-numeric (e.g. "f001").
 */
const movementSchema = new Schema(
  {
    // Ingestion metadata
    empresa: { type: String, enum: EMPRESAS, required: true },
    periodo: { type: String, required: true, match: /^\d{2}\/\d{4}$/ }, // "MM/YYYY"
    fechaISO: { type: Date, required: true },
    // `archivo` is the source file name for ledger/cmv-calc. For manual
    // movements we use the sentinel '(manual)' so the column stays non-null.
    archivo: { type: String, required: true },
    // Manual movements have no batch association — they outlive any batch.
    ingestionBatchId: {
      type: Schema.Types.ObjectId,
      ref: 'IngestionBatch',
      default: null,
    },
    sourceType: {
      type: String,
      enum: ['ledger', 'cmv-calc', 'manual'],
      default: 'ledger',
      required: true,
    },

    // Raw ledger fields
    asiento: { type: Number, required: true },
    numeroCuenta: { type: String, required: true, trim: true },
    nombreCuenta: { type: String, required: true, trim: true },
    numeroSubcuenta: { type: String, default: null, trim: true },
    nombreSubcuenta: { type: String, default: null, trim: true },
    rubro: { type: String, enum: RUBROS, required: true },
    detalle: { type: String, default: '', trim: true },
    debe: { type: Number, default: 0 },
    haber: { type: Number, default: 0 },

    // Enrichment
    numeroCuentaReimputada: { type: String, required: true, trim: true },
    nombreCuentaReimputada: { type: String, required: true, trim: true },
    rubroReimputada: { type: String, enum: RUBROS, required: true },
    subrubro: { type: String, default: null, trim: true },
    anulacion: { type: Boolean, default: false },
  },
  { timestamps: true, collection: 'movements' },
);

// Indexes for common queries
movementSchema.index({ empresa: 1, periodo: 1 });
movementSchema.index({ ingestionBatchId: 1 });
movementSchema.index({ periodo: 1, rubroReimputada: 1, numeroCuentaReimputada: 1 });
movementSchema.index({ periodo: 1, subrubro: 1 });
movementSchema.index({ fechaISO: 1 });
// For listing / managing manual movements
movementSchema.index({ sourceType: 1, periodo: 1 });

export type Movement = {
  _id: Types.ObjectId;
  empresa: Empresa;
  periodo: string;
  fechaISO: Date;
  archivo: string;
  ingestionBatchId: Types.ObjectId | null;
  sourceType: 'ledger' | 'cmv-calc' | 'manual';
  asiento: number;
  numeroCuenta: string;
  nombreCuenta: string;
  numeroSubcuenta: string | null;
  nombreSubcuenta: string | null;
  rubro: Rubro;
  detalle: string;
  debe: number;
  haber: number;
  numeroCuentaReimputada: string;
  nombreCuentaReimputada: string;
  rubroReimputada: Rubro;
  subrubro: string | null;
  anulacion: boolean;
  createdAt?: Date;
  updatedAt?: Date;
};
export const MovementModel = model('Movement', movementSchema);
